package com.github.pooryam92.vimcoach.features.tips.unit.loading.infra.parsing

import com.github.pooryam92.vimcoach.features.tips.application.ideavimrc.IdeaVimRcAppendPlan
import com.github.pooryam92.vimcoach.features.tips.application.loading.infra.parsing.TipJsonParser
import com.github.pooryam92.vimcoach.features.tips.domain.TipMode
import com.github.pooryam92.vimcoach.features.tips.domain.VimTip
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Contract between the committed `tips/vim_tips_min.json` and the runtime that consumes it.
 * The parser is lenient and silently drops or strips bad data, so these checks catch a generator
 * regression that would otherwise ship as missing tips, missing labels or a dead .ideavimrc button.
 *
 * Deliberately does not compare against `tips/categories/`: the min file is regenerated by CI and
 * may lag the sources locally.
 */
class BundledTipsContractUnitTest {

    private val minJson: File = locateMinJson()
    private val rawTips: List<JsonObject> =
        JsonParser.parseString(minJson.readText()).asJsonObject.getAsJsonArray("tips").map { it.asJsonObject }
    private val parsedTips: List<VimTip> = minJson.inputStream().use(TipJsonParser::parseTipsJson)

    @Test
    fun everyTipParses() {
        val parsedSummaries = parsedTips.map(VimTip::summary).toSet()
        val dropped = rawTips.map(::rawSummary).filterNot { it in parsedSummaries }
        assertNoViolations("tips dropped by TipJsonParser", dropped)
        assertTrue("parser returned more tips than the file holds", parsedTips.size <= rawTips.size)
    }

    @Test
    fun everyConfigYieldsANonEmptyAppendPlan() {
        val rawConfigSummaries = rawTips.filter { it.has("config") }.map(::rawSummary)
        val parsedBySummary = parsedTips.associateBy(VimTip::summary)
        val violations = rawConfigSummaries.filter { summary ->
            val lines = parsedBySummary[summary]?.config?.lines ?: return@filter true
            val plan = IdeaVimRcAppendPlan.determine(existingText = "", configLines = lines)
            plan !is IdeaVimRcAppendPlan.Plan.Append || plan.addedCount == 0
        }
        assertNoViolations("tips whose config yields no append plan", violations)
    }

    @Test
    fun everyModeMapsToATipMode() {
        val violations = rawTips.filter { it.has("mode") }.mapNotNull { tip ->
            val mode = tip.get("mode")
            val wire = mode.takeIf { it.isJsonPrimitive && it.asJsonPrimitive.isString }?.asString
            if (TipMode.fromWire(wire) == null) "${rawSummary(tip)}: $mode" else null
        }
        assertNoViolations("tips with an unknown mode", violations)
    }

    @Test
    fun advancedIsTrueWhenPresent() {
        val violations = rawTips.filter { it.has("advanced") }.mapNotNull { tip ->
            val advanced = tip.get("advanced")
            val isTrue = advanced.isJsonPrimitive && advanced.asJsonPrimitive.isBoolean && advanced.asBoolean
            if (isTrue) null else "${rawSummary(tip)}: $advanced"
        }
        assertNoViolations("tips whose advanced flag is not boolean true", violations)
    }

    @Test
    fun summariesAreUnique() {
        val violations = rawTips.map(::rawSummary)
            .groupingBy { it }.eachCount()
            .filter { it.value > 1 }
            .map { "\"${it.key}\" appears ${it.value} times" }
        assertNoViolations("duplicate summaries", violations)
    }

    @Test
    fun everyCategoryIsKnown() {
        val violations = parsedTips.flatMap { tip ->
            tip.category.filterNot(KNOWN_CATEGORIES::contains).map { "${tip.summary}: $it" }
        }
        assertNoViolations("tips with an unknown category", violations)
    }

    private fun rawSummary(tip: JsonObject): String =
        tip.get("summary")?.takeIf { it.isJsonPrimitive }?.asString?.trim().orEmpty()

    private fun assertNoViolations(what: String, violations: List<String>) {
        assertTrue(
            "${violations.size} $what in ${minJson.path}:\n" + violations.joinToString("\n") { "  - $it" },
            violations.isEmpty()
        )
    }

    private companion object {
        val KNOWN_CATEGORIES = setOf(
            "cmdline", "editing", "files", "ideavim", "insert", "mappings", "navigation",
            "options", "pattern", "plugins", "registers", "repeat", "visual", "windows",
        )

        // Gradle's test working directory is not guaranteed to be the repo root.
        fun locateMinJson(): File {
            val start = File(System.getProperty("user.dir")).absoluteFile
            return generateSequence(start) { it.parentFile }
                .map { File(it, "tips/vim_tips_min.json") }
                .firstOrNull(File::isFile)
                ?: error("tips/vim_tips_min.json not found in $start or any parent directory")
        }
    }
}
